sed 's/<i>Ar<b\/>/<par n="P__ar_er"\/><i>/g' | \
sed 's/<i>Gw/<par n="initial-Gw"\/><i>/g' | \
sed 's/<i>B/<par n="initial-B"\/><i>/g' | \
sed 's/<i>D/<par n="initial-D"\/><i>/g' |\
sed 's/<i>G/<par n="initial-G"\/><i>/g' |\
sed 's/<i>K/<par n="initial-K"\/><i>/g'  |\
sed 's/<i>M/<par n="initial-M"\/><i>/g' |\
sed 's/<i>P/<par n="initial-P"\/><i>/g' |\
sed 's/<i>T/<par n="initial-T"\/><i>/g' 
